// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Players.proto

package test;

public final class PlayersOuterClass {
  private PlayersOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PlayerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:test.Player)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 PlayerId = 1;</code>
     * @return The playerId.
     */
    int getPlayerId();

    /**
     * <code>string PlayerName = 2;</code>
     * @return The playerName.
     */
    java.lang.String getPlayerName();
    /**
     * <code>string PlayerName = 2;</code>
     * @return The bytes for playerName.
     */
    com.google.protobuf.ByteString
        getPlayerNameBytes();

    /**
     * <code>int32 PlayerNumber = 3;</code>
     * @return The playerNumber.
     */
    int getPlayerNumber();

    /**
     * <code>string PlayerPosition = 4;</code>
     * @return The playerPosition.
     */
    java.lang.String getPlayerPosition();
    /**
     * <code>string PlayerPosition = 4;</code>
     * @return The bytes for playerPosition.
     */
    com.google.protobuf.ByteString
        getPlayerPositionBytes();
  }
  /**
   * Protobuf type {@code test.Player}
   */
  public static final class Player extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:test.Player)
      PlayerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Player.newBuilder() to construct.
    private Player(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Player() {
      playerName_ = "";
      playerPosition_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Player();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Player(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              playerId_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              playerName_ = s;
              break;
            }
            case 24: {

              playerNumber_ = input.readInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              playerPosition_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return test.PlayersOuterClass.internal_static_test_Player_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return test.PlayersOuterClass.internal_static_test_Player_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              test.PlayersOuterClass.Player.class, test.PlayersOuterClass.Player.Builder.class);
    }

    public static final int PLAYERID_FIELD_NUMBER = 1;
    private int playerId_;
    /**
     * <code>int32 PlayerId = 1;</code>
     * @return The playerId.
     */
    @java.lang.Override
    public int getPlayerId() {
      return playerId_;
    }

    public static final int PLAYERNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object playerName_;
    /**
     * <code>string PlayerName = 2;</code>
     * @return The playerName.
     */
    @java.lang.Override
    public java.lang.String getPlayerName() {
      java.lang.Object ref = playerName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        playerName_ = s;
        return s;
      }
    }
    /**
     * <code>string PlayerName = 2;</code>
     * @return The bytes for playerName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPlayerNameBytes() {
      java.lang.Object ref = playerName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        playerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PLAYERNUMBER_FIELD_NUMBER = 3;
    private int playerNumber_;
    /**
     * <code>int32 PlayerNumber = 3;</code>
     * @return The playerNumber.
     */
    @java.lang.Override
    public int getPlayerNumber() {
      return playerNumber_;
    }

    public static final int PLAYERPOSITION_FIELD_NUMBER = 4;
    private volatile java.lang.Object playerPosition_;
    /**
     * <code>string PlayerPosition = 4;</code>
     * @return The playerPosition.
     */
    @java.lang.Override
    public java.lang.String getPlayerPosition() {
      java.lang.Object ref = playerPosition_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        playerPosition_ = s;
        return s;
      }
    }
    /**
     * <code>string PlayerPosition = 4;</code>
     * @return The bytes for playerPosition.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPlayerPositionBytes() {
      java.lang.Object ref = playerPosition_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        playerPosition_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (playerId_ != 0) {
        output.writeInt32(1, playerId_);
      }
      if (!getPlayerNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, playerName_);
      }
      if (playerNumber_ != 0) {
        output.writeInt32(3, playerNumber_);
      }
      if (!getPlayerPositionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, playerPosition_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (playerId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, playerId_);
      }
      if (!getPlayerNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, playerName_);
      }
      if (playerNumber_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, playerNumber_);
      }
      if (!getPlayerPositionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, playerPosition_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof test.PlayersOuterClass.Player)) {
        return super.equals(obj);
      }
      test.PlayersOuterClass.Player other = (test.PlayersOuterClass.Player) obj;

      if (getPlayerId()
          != other.getPlayerId()) return false;
      if (!getPlayerName()
          .equals(other.getPlayerName())) return false;
      if (getPlayerNumber()
          != other.getPlayerNumber()) return false;
      if (!getPlayerPosition()
          .equals(other.getPlayerPosition())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PLAYERID_FIELD_NUMBER;
      hash = (53 * hash) + getPlayerId();
      hash = (37 * hash) + PLAYERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getPlayerName().hashCode();
      hash = (37 * hash) + PLAYERNUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getPlayerNumber();
      hash = (37 * hash) + PLAYERPOSITION_FIELD_NUMBER;
      hash = (53 * hash) + getPlayerPosition().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static test.PlayersOuterClass.Player parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.PlayersOuterClass.Player parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.PlayersOuterClass.Player parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.PlayersOuterClass.Player parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.PlayersOuterClass.Player parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.PlayersOuterClass.Player parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.PlayersOuterClass.Player parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static test.PlayersOuterClass.Player parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static test.PlayersOuterClass.Player parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static test.PlayersOuterClass.Player parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static test.PlayersOuterClass.Player parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static test.PlayersOuterClass.Player parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(test.PlayersOuterClass.Player prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code test.Player}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:test.Player)
        test.PlayersOuterClass.PlayerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return test.PlayersOuterClass.internal_static_test_Player_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return test.PlayersOuterClass.internal_static_test_Player_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                test.PlayersOuterClass.Player.class, test.PlayersOuterClass.Player.Builder.class);
      }

      // Construct using test.PlayersOuterClass.Player.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        playerId_ = 0;

        playerName_ = "";

        playerNumber_ = 0;

        playerPosition_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return test.PlayersOuterClass.internal_static_test_Player_descriptor;
      }

      @java.lang.Override
      public test.PlayersOuterClass.Player getDefaultInstanceForType() {
        return test.PlayersOuterClass.Player.getDefaultInstance();
      }

      @java.lang.Override
      public test.PlayersOuterClass.Player build() {
        test.PlayersOuterClass.Player result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public test.PlayersOuterClass.Player buildPartial() {
        test.PlayersOuterClass.Player result = new test.PlayersOuterClass.Player(this);
        result.playerId_ = playerId_;
        result.playerName_ = playerName_;
        result.playerNumber_ = playerNumber_;
        result.playerPosition_ = playerPosition_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof test.PlayersOuterClass.Player) {
          return mergeFrom((test.PlayersOuterClass.Player)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(test.PlayersOuterClass.Player other) {
        if (other == test.PlayersOuterClass.Player.getDefaultInstance()) return this;
        if (other.getPlayerId() != 0) {
          setPlayerId(other.getPlayerId());
        }
        if (!other.getPlayerName().isEmpty()) {
          playerName_ = other.playerName_;
          onChanged();
        }
        if (other.getPlayerNumber() != 0) {
          setPlayerNumber(other.getPlayerNumber());
        }
        if (!other.getPlayerPosition().isEmpty()) {
          playerPosition_ = other.playerPosition_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        test.PlayersOuterClass.Player parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (test.PlayersOuterClass.Player) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int playerId_ ;
      /**
       * <code>int32 PlayerId = 1;</code>
       * @return The playerId.
       */
      @java.lang.Override
      public int getPlayerId() {
        return playerId_;
      }
      /**
       * <code>int32 PlayerId = 1;</code>
       * @param value The playerId to set.
       * @return This builder for chaining.
       */
      public Builder setPlayerId(int value) {
        
        playerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 PlayerId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPlayerId() {
        
        playerId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object playerName_ = "";
      /**
       * <code>string PlayerName = 2;</code>
       * @return The playerName.
       */
      public java.lang.String getPlayerName() {
        java.lang.Object ref = playerName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          playerName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string PlayerName = 2;</code>
       * @return The bytes for playerName.
       */
      public com.google.protobuf.ByteString
          getPlayerNameBytes() {
        java.lang.Object ref = playerName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          playerName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string PlayerName = 2;</code>
       * @param value The playerName to set.
       * @return This builder for chaining.
       */
      public Builder setPlayerName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        playerName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string PlayerName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPlayerName() {
        
        playerName_ = getDefaultInstance().getPlayerName();
        onChanged();
        return this;
      }
      /**
       * <code>string PlayerName = 2;</code>
       * @param value The bytes for playerName to set.
       * @return This builder for chaining.
       */
      public Builder setPlayerNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        playerName_ = value;
        onChanged();
        return this;
      }

      private int playerNumber_ ;
      /**
       * <code>int32 PlayerNumber = 3;</code>
       * @return The playerNumber.
       */
      @java.lang.Override
      public int getPlayerNumber() {
        return playerNumber_;
      }
      /**
       * <code>int32 PlayerNumber = 3;</code>
       * @param value The playerNumber to set.
       * @return This builder for chaining.
       */
      public Builder setPlayerNumber(int value) {
        
        playerNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 PlayerNumber = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPlayerNumber() {
        
        playerNumber_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object playerPosition_ = "";
      /**
       * <code>string PlayerPosition = 4;</code>
       * @return The playerPosition.
       */
      public java.lang.String getPlayerPosition() {
        java.lang.Object ref = playerPosition_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          playerPosition_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string PlayerPosition = 4;</code>
       * @return The bytes for playerPosition.
       */
      public com.google.protobuf.ByteString
          getPlayerPositionBytes() {
        java.lang.Object ref = playerPosition_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          playerPosition_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string PlayerPosition = 4;</code>
       * @param value The playerPosition to set.
       * @return This builder for chaining.
       */
      public Builder setPlayerPosition(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        playerPosition_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string PlayerPosition = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPlayerPosition() {
        
        playerPosition_ = getDefaultInstance().getPlayerPosition();
        onChanged();
        return this;
      }
      /**
       * <code>string PlayerPosition = 4;</code>
       * @param value The bytes for playerPosition to set.
       * @return This builder for chaining.
       */
      public Builder setPlayerPositionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        playerPosition_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:test.Player)
    }

    // @@protoc_insertion_point(class_scope:test.Player)
    private static final test.PlayersOuterClass.Player DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new test.PlayersOuterClass.Player();
    }

    public static test.PlayersOuterClass.Player getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Player>
        PARSER = new com.google.protobuf.AbstractParser<Player>() {
      @java.lang.Override
      public Player parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Player(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Player> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Player> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public test.PlayersOuterClass.Player getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PlayersOrBuilder extends
      // @@protoc_insertion_point(interface_extends:test.Players)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .test.Player PlayerList = 1;</code>
     */
    java.util.List<test.PlayersOuterClass.Player> 
        getPlayerListList();
    /**
     * <code>repeated .test.Player PlayerList = 1;</code>
     */
    test.PlayersOuterClass.Player getPlayerList(int index);
    /**
     * <code>repeated .test.Player PlayerList = 1;</code>
     */
    int getPlayerListCount();
    /**
     * <code>repeated .test.Player PlayerList = 1;</code>
     */
    java.util.List<? extends test.PlayersOuterClass.PlayerOrBuilder> 
        getPlayerListOrBuilderList();
    /**
     * <code>repeated .test.Player PlayerList = 1;</code>
     */
    test.PlayersOuterClass.PlayerOrBuilder getPlayerListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code test.Players}
   */
  public static final class Players extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:test.Players)
      PlayersOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Players.newBuilder() to construct.
    private Players(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Players() {
      playerList_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Players();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Players(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                playerList_ = new java.util.ArrayList<test.PlayersOuterClass.Player>();
                mutable_bitField0_ |= 0x00000001;
              }
              playerList_.add(
                  input.readMessage(test.PlayersOuterClass.Player.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          playerList_ = java.util.Collections.unmodifiableList(playerList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return test.PlayersOuterClass.internal_static_test_Players_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return test.PlayersOuterClass.internal_static_test_Players_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              test.PlayersOuterClass.Players.class, test.PlayersOuterClass.Players.Builder.class);
    }

    public static final int PLAYERLIST_FIELD_NUMBER = 1;
    private java.util.List<test.PlayersOuterClass.Player> playerList_;
    /**
     * <code>repeated .test.Player PlayerList = 1;</code>
     */
    @java.lang.Override
    public java.util.List<test.PlayersOuterClass.Player> getPlayerListList() {
      return playerList_;
    }
    /**
     * <code>repeated .test.Player PlayerList = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends test.PlayersOuterClass.PlayerOrBuilder> 
        getPlayerListOrBuilderList() {
      return playerList_;
    }
    /**
     * <code>repeated .test.Player PlayerList = 1;</code>
     */
    @java.lang.Override
    public int getPlayerListCount() {
      return playerList_.size();
    }
    /**
     * <code>repeated .test.Player PlayerList = 1;</code>
     */
    @java.lang.Override
    public test.PlayersOuterClass.Player getPlayerList(int index) {
      return playerList_.get(index);
    }
    /**
     * <code>repeated .test.Player PlayerList = 1;</code>
     */
    @java.lang.Override
    public test.PlayersOuterClass.PlayerOrBuilder getPlayerListOrBuilder(
        int index) {
      return playerList_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < playerList_.size(); i++) {
        output.writeMessage(1, playerList_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < playerList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, playerList_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof test.PlayersOuterClass.Players)) {
        return super.equals(obj);
      }
      test.PlayersOuterClass.Players other = (test.PlayersOuterClass.Players) obj;

      if (!getPlayerListList()
          .equals(other.getPlayerListList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getPlayerListCount() > 0) {
        hash = (37 * hash) + PLAYERLIST_FIELD_NUMBER;
        hash = (53 * hash) + getPlayerListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static test.PlayersOuterClass.Players parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.PlayersOuterClass.Players parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.PlayersOuterClass.Players parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.PlayersOuterClass.Players parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.PlayersOuterClass.Players parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.PlayersOuterClass.Players parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.PlayersOuterClass.Players parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static test.PlayersOuterClass.Players parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static test.PlayersOuterClass.Players parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static test.PlayersOuterClass.Players parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static test.PlayersOuterClass.Players parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static test.PlayersOuterClass.Players parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(test.PlayersOuterClass.Players prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code test.Players}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:test.Players)
        test.PlayersOuterClass.PlayersOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return test.PlayersOuterClass.internal_static_test_Players_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return test.PlayersOuterClass.internal_static_test_Players_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                test.PlayersOuterClass.Players.class, test.PlayersOuterClass.Players.Builder.class);
      }

      // Construct using test.PlayersOuterClass.Players.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPlayerListFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (playerListBuilder_ == null) {
          playerList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          playerListBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return test.PlayersOuterClass.internal_static_test_Players_descriptor;
      }

      @java.lang.Override
      public test.PlayersOuterClass.Players getDefaultInstanceForType() {
        return test.PlayersOuterClass.Players.getDefaultInstance();
      }

      @java.lang.Override
      public test.PlayersOuterClass.Players build() {
        test.PlayersOuterClass.Players result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public test.PlayersOuterClass.Players buildPartial() {
        test.PlayersOuterClass.Players result = new test.PlayersOuterClass.Players(this);
        int from_bitField0_ = bitField0_;
        if (playerListBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            playerList_ = java.util.Collections.unmodifiableList(playerList_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.playerList_ = playerList_;
        } else {
          result.playerList_ = playerListBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof test.PlayersOuterClass.Players) {
          return mergeFrom((test.PlayersOuterClass.Players)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(test.PlayersOuterClass.Players other) {
        if (other == test.PlayersOuterClass.Players.getDefaultInstance()) return this;
        if (playerListBuilder_ == null) {
          if (!other.playerList_.isEmpty()) {
            if (playerList_.isEmpty()) {
              playerList_ = other.playerList_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePlayerListIsMutable();
              playerList_.addAll(other.playerList_);
            }
            onChanged();
          }
        } else {
          if (!other.playerList_.isEmpty()) {
            if (playerListBuilder_.isEmpty()) {
              playerListBuilder_.dispose();
              playerListBuilder_ = null;
              playerList_ = other.playerList_;
              bitField0_ = (bitField0_ & ~0x00000001);
              playerListBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPlayerListFieldBuilder() : null;
            } else {
              playerListBuilder_.addAllMessages(other.playerList_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        test.PlayersOuterClass.Players parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (test.PlayersOuterClass.Players) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<test.PlayersOuterClass.Player> playerList_ =
        java.util.Collections.emptyList();
      private void ensurePlayerListIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          playerList_ = new java.util.ArrayList<test.PlayersOuterClass.Player>(playerList_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          test.PlayersOuterClass.Player, test.PlayersOuterClass.Player.Builder, test.PlayersOuterClass.PlayerOrBuilder> playerListBuilder_;

      /**
       * <code>repeated .test.Player PlayerList = 1;</code>
       */
      public java.util.List<test.PlayersOuterClass.Player> getPlayerListList() {
        if (playerListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(playerList_);
        } else {
          return playerListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .test.Player PlayerList = 1;</code>
       */
      public int getPlayerListCount() {
        if (playerListBuilder_ == null) {
          return playerList_.size();
        } else {
          return playerListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .test.Player PlayerList = 1;</code>
       */
      public test.PlayersOuterClass.Player getPlayerList(int index) {
        if (playerListBuilder_ == null) {
          return playerList_.get(index);
        } else {
          return playerListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .test.Player PlayerList = 1;</code>
       */
      public Builder setPlayerList(
          int index, test.PlayersOuterClass.Player value) {
        if (playerListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePlayerListIsMutable();
          playerList_.set(index, value);
          onChanged();
        } else {
          playerListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .test.Player PlayerList = 1;</code>
       */
      public Builder setPlayerList(
          int index, test.PlayersOuterClass.Player.Builder builderForValue) {
        if (playerListBuilder_ == null) {
          ensurePlayerListIsMutable();
          playerList_.set(index, builderForValue.build());
          onChanged();
        } else {
          playerListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .test.Player PlayerList = 1;</code>
       */
      public Builder addPlayerList(test.PlayersOuterClass.Player value) {
        if (playerListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePlayerListIsMutable();
          playerList_.add(value);
          onChanged();
        } else {
          playerListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .test.Player PlayerList = 1;</code>
       */
      public Builder addPlayerList(
          int index, test.PlayersOuterClass.Player value) {
        if (playerListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePlayerListIsMutable();
          playerList_.add(index, value);
          onChanged();
        } else {
          playerListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .test.Player PlayerList = 1;</code>
       */
      public Builder addPlayerList(
          test.PlayersOuterClass.Player.Builder builderForValue) {
        if (playerListBuilder_ == null) {
          ensurePlayerListIsMutable();
          playerList_.add(builderForValue.build());
          onChanged();
        } else {
          playerListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .test.Player PlayerList = 1;</code>
       */
      public Builder addPlayerList(
          int index, test.PlayersOuterClass.Player.Builder builderForValue) {
        if (playerListBuilder_ == null) {
          ensurePlayerListIsMutable();
          playerList_.add(index, builderForValue.build());
          onChanged();
        } else {
          playerListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .test.Player PlayerList = 1;</code>
       */
      public Builder addAllPlayerList(
          java.lang.Iterable<? extends test.PlayersOuterClass.Player> values) {
        if (playerListBuilder_ == null) {
          ensurePlayerListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, playerList_);
          onChanged();
        } else {
          playerListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .test.Player PlayerList = 1;</code>
       */
      public Builder clearPlayerList() {
        if (playerListBuilder_ == null) {
          playerList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          playerListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .test.Player PlayerList = 1;</code>
       */
      public Builder removePlayerList(int index) {
        if (playerListBuilder_ == null) {
          ensurePlayerListIsMutable();
          playerList_.remove(index);
          onChanged();
        } else {
          playerListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .test.Player PlayerList = 1;</code>
       */
      public test.PlayersOuterClass.Player.Builder getPlayerListBuilder(
          int index) {
        return getPlayerListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .test.Player PlayerList = 1;</code>
       */
      public test.PlayersOuterClass.PlayerOrBuilder getPlayerListOrBuilder(
          int index) {
        if (playerListBuilder_ == null) {
          return playerList_.get(index);  } else {
          return playerListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .test.Player PlayerList = 1;</code>
       */
      public java.util.List<? extends test.PlayersOuterClass.PlayerOrBuilder> 
           getPlayerListOrBuilderList() {
        if (playerListBuilder_ != null) {
          return playerListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(playerList_);
        }
      }
      /**
       * <code>repeated .test.Player PlayerList = 1;</code>
       */
      public test.PlayersOuterClass.Player.Builder addPlayerListBuilder() {
        return getPlayerListFieldBuilder().addBuilder(
            test.PlayersOuterClass.Player.getDefaultInstance());
      }
      /**
       * <code>repeated .test.Player PlayerList = 1;</code>
       */
      public test.PlayersOuterClass.Player.Builder addPlayerListBuilder(
          int index) {
        return getPlayerListFieldBuilder().addBuilder(
            index, test.PlayersOuterClass.Player.getDefaultInstance());
      }
      /**
       * <code>repeated .test.Player PlayerList = 1;</code>
       */
      public java.util.List<test.PlayersOuterClass.Player.Builder> 
           getPlayerListBuilderList() {
        return getPlayerListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          test.PlayersOuterClass.Player, test.PlayersOuterClass.Player.Builder, test.PlayersOuterClass.PlayerOrBuilder> 
          getPlayerListFieldBuilder() {
        if (playerListBuilder_ == null) {
          playerListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              test.PlayersOuterClass.Player, test.PlayersOuterClass.Player.Builder, test.PlayersOuterClass.PlayerOrBuilder>(
                  playerList_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          playerList_ = null;
        }
        return playerListBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:test.Players)
    }

    // @@protoc_insertion_point(class_scope:test.Players)
    private static final test.PlayersOuterClass.Players DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new test.PlayersOuterClass.Players();
    }

    public static test.PlayersOuterClass.Players getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Players>
        PARSER = new com.google.protobuf.AbstractParser<Players>() {
      @java.lang.Override
      public Players parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Players(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Players> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Players> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public test.PlayersOuterClass.Players getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_test_Player_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_test_Player_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_test_Players_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_test_Players_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rPlayers.proto\022\004test\"\\\n\006Player\022\020\n\010Playe" +
      "rId\030\001 \001(\005\022\022\n\nPlayerName\030\002 \001(\t\022\024\n\014PlayerN" +
      "umber\030\003 \001(\005\022\026\n\016PlayerPosition\030\004 \001(\t\"+\n\007P" +
      "layers\022 \n\nPlayerList\030\001 \003(\0132\014.test.Player" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_test_Player_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_test_Player_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_test_Player_descriptor,
        new java.lang.String[] { "PlayerId", "PlayerName", "PlayerNumber", "PlayerPosition", });
    internal_static_test_Players_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_test_Players_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_test_Players_descriptor,
        new java.lang.String[] { "PlayerList", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
